### ISSUE TITLE
设置缩放后，子级地图偏移

### ISSUE THREAD

**Issue by liuxinju** [flute/echarts3-chinese-map-drill-down#3]
请教下您，我将地图设置成可缩放之后，进入下一级，地图就会有偏移，若是放大的多，地图直接在画布上找不到，这个问题该怎么解决呢

**Comment by flute** [comment]
@liuxinju echarts有自动根据显示内容调整中心点及缩放比例的方法，你可以去查查文档。

**Comment by liuxinju** [comment]
@flute 是的，我也感得是有的，但我找了两天，也没有找出合适的解决方案，你能帮忙看下吗？拜托您

**Comment by liuxinju** [comment]
部署完之后发现这个问题已经不存在了，非常感谢您！

**Comment by cqm1994617** [comment]
我这边是通过restore来实现的
```
chart.dispatchAction({
  type: "restore"
});
//之后设置子级地图
```
