### ISSUE TITLE
仓库下载到本地，index.html打开什么都没有显示

### ISSUE THREAD

**Issue by comeCU** [flute/echarts3-chinese-map-drill-down#4]
您好！我将他下载到本地，index.html打开无法显示出您图片中的效果，请问是echart版本的问题吗？
![echart3](https://user-images.githubusercontent.com/30254171/49361810-daaed700-f717-11e8-9766-6abda1c61401.png)

**Comment by flute** [comment]
页面中涉及到加载ison文件的http请求，所以需要启动一个nginx/apache...等的服务，通过server访问页面。
